"""Metrics. Calibration reads prob_selected, discrimination reads confidence."""

from plumbline.metrics.calibration import (
    Bin,
    Binning,
    FloorBand,
    brier,
    calibration_floor,
    ece,
    is_distinguishable,
    mce,
    multiclass_brier,
    reliability,
    synthetic_floor,
    verdict,
)
from plumbline.metrics.cascade import (
    CascadeRow,
    candidate_thresholds,
    cascade_sweep,
    optimal_threshold,
)
from plumbline.metrics.cost import (
    CostSummary,
    Pricing,
    PricingTable,
    cost_of,
    estimate_case_cost,
    pricing_for,
)
from plumbline.metrics.discrimination import (
    DEFAULT_THRESHOLDS,
    SweepRow,
    auroc,
    threshold_sweep,
)
from plumbline.metrics.latency import LatencySummary
from plumbline.metrics.recalibration import (
    MetricSet,
    RecalibrationResult,
    Split,
    apply_temperature_binary,
    fit_temperature_binary,
    fit_temperature_multiclass,
    make_split,
    recalibrate,
)

__all__ = [
    "DEFAULT_THRESHOLDS",
    "Bin",
    "Binning",
    "CascadeRow",
    "CostSummary",
    "FloorBand",
    "LatencySummary",
    "MetricSet",
    "Pricing",
    "PricingTable",
    "RecalibrationResult",
    "Split",
    "SweepRow",
    "apply_temperature_binary",
    "auroc",
    "brier",
    "calibration_floor",
    "candidate_thresholds",
    "cascade_sweep",
    "cost_of",
    "ece",
    "estimate_case_cost",
    "fit_temperature_binary",
    "fit_temperature_multiclass",
    "is_distinguishable",
    "make_split",
    "mce",
    "multiclass_brier",
    "optimal_threshold",
    "pricing_for",
    "recalibrate",
    "reliability",
    "synthetic_floor",
    "threshold_sweep",
    "verdict",
]
